### ISSUE TITLE
Rename `ChainlinkOracle` as it's misleading

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-blue-oracles#69]
<img width="533" alt="Screenshot 2024-02-02 at 10 27 55" src="https://github.com/morpho-org/morpho-blue-oracles/assets/44097430/db80a848-10a6-4898-8d16-74c07644d0a6">

**Comment by Rubilmax** [comment]
`ChainlinkCompliantOracle`?

**Comment by MerlinEgalite** [comment]
I was thinking about first `ChainlinkCompliantOracleWrapper` but yours is shorter. But it's perhaps less clear that it not limited to one single feed

**Comment by adhusson** [comment]
Could include version number starting from 2 eg `ChainLinkCompliantOracleV2` (otherwise you come to the repo to verify and which folder do you open?)
